netflix=["STRANGER THINGS ","PEAKY BLINDER","MONEY HIEST","SQUAD GAME"]
movie=["JOHN WICK","AVENGERS","FAST AND FURIOUS","TRANSFORMERS"]
user=str(input("WHAT KIND OF SHOW DO YOUR LIKE MOVIE OR TV SERIES ? "))
if user=="TV SERIES":
    print("THIS IS MOVIE LIST OUR RECCOMENDATION ENGINE GET FOR YOU:",netflix)
elif user=="MOVIES":
    print("THIS IS TV SERIES LIST OUR RECCOMENDATION ENGINE GET FOR YOU:",movie)
